apiVersion: v2
name: archive-node
description: A Helm chart for Mina Protocol's archive node
type: application
version: 1.0.23
appVersion: 1.16.0
annotations:
  artifacthub.io/changes: |
    - Develop changes adjusted for compatible use, 1.0.X = compatible
dependencies:
  - name: postgresql
    version: "*"
    repository: "https://charts.bitnami.com/bitnami"
    condition: archive.enablePostgresDB
  - name: common-utilities
    version: "*"
    repository: "https://coda-charts.storage.googleapis.com"
icon: https://storage.googleapis.com/coda-charts/Mina_Icon_Secondary_RGB_Black.png
keywords:
- archive
- postgres
- mina
- testnet
home: https://minaprotocol.com/
sources:
- https://github.com/MinaProtocol/mina/tree/compatible/helm/archive-node
